{{- if eq .Values.postgres.mode "operator" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garden.fullname" . }}-cnpg-superuser-secret
type: Opaque
data:
  username: cG9zdGdyZXM= # postgres
  password: {{ .Values.postgres.superuserpassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garden.fullname" . }}-cnpg-user-secret
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
{{- end }}
