{{- if eq .Values.postgres.mode "standalone" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garden.fullname" . }}-pg-secret
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
{{- end }}
